# These are supported funding model platforms
custom: ["https://github.com/sponsors/BiancoRoyal", "https://opencollective.com/node-red-contrib-modbus", "https://plus4nodered.com/", "https://p4nr.com/"]
